# TCL File Generated by Component Editor 13.0sp1
# Tue Apr 15 09:19:56 CEST 2014
# DO NOT MODIFY


# 
# TofPet_Avalon_MM_IF "TofPet_Avalon_MM_IF" v1.0
#  2014.04.15.09:19:56
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module TofPet_Avalon_MM_IF
# 
set_module_property DESCRIPTION ""
set_module_property NAME TofPet_Avalon_MM_IF
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME TofPet_Avalon_MM_IF
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL TofPetInterface_AvalonIF
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file TofPet_Avalon_MM_IF.v VERILOG PATH TofPet_Avalon_MM_IF.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock_sink
set_interface_property avalon_slave_0 associatedReset reset_sink
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 0
set_interface_property avalon_slave_0 readWaitTime 0
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 avalon_addr address Input 4
add_interface_port avalon_slave_0 avalon_data_in writedata Input 32
add_interface_port avalon_slave_0 avalon_data_out readdata Output 32
add_interface_port avalon_slave_0 avalon_cs chipselect Input 1
add_interface_port avalon_slave_0 avalon_readn read_n Input 1
add_interface_port avalon_slave_0 avalon_writen write_n Input 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point clock_sink
# 
add_interface clock_sink clock end
set_interface_property clock_sink clockRate 0
set_interface_property clock_sink ENABLED true
set_interface_property clock_sink EXPORT_OF ""
set_interface_property clock_sink PORT_NAME_MAP ""
set_interface_property clock_sink SVD_ADDRESS_GROUP ""

add_interface_port clock_sink CK clk Input 1


# 
# connection point reset_sink
# 
add_interface reset_sink reset end
set_interface_property reset_sink associatedClock clock_sink
set_interface_property reset_sink synchronousEdges DEASSERT
set_interface_property reset_sink ENABLED true
set_interface_property reset_sink EXPORT_OF ""
set_interface_property reset_sink PORT_NAME_MAP ""
set_interface_property reset_sink SVD_ADDRESS_GROUP ""

add_interface_port reset_sink RESETb reset_n Input 1


# 
# connection point TofPet_Conduit
# 
add_interface TofPet_Conduit conduit end
set_interface_property TofPet_Conduit associatedClock clock_sink
set_interface_property TofPet_Conduit associatedReset reset_sink
set_interface_property TofPet_Conduit ENABLED true
set_interface_property TofPet_Conduit EXPORT_OF ""
set_interface_property TofPet_Conduit PORT_NAME_MAP ""
set_interface_property TofPet_Conduit SVD_ADDRESS_GROUP ""

add_interface_port TofPet_Conduit DATA_OUT0 export Input 32
add_interface_port TofPet_Conduit EMPTY0 export Input 1
add_interface_port TofPet_Conduit FULL0 export Input 1
add_interface_port TofPet_Conduit DATA_OUT1 export Input 32
add_interface_port TofPet_Conduit EMPTY1 export Input 1
add_interface_port TofPet_Conduit FULL1 export Input 1
add_interface_port TofPet_Conduit DATA_OUT2 export Input 32
add_interface_port TofPet_Conduit EMPTY2 export Input 1
add_interface_port TofPet_Conduit FULL2 export Input 1
add_interface_port TofPet_Conduit DATA_OUT3 export Input 32
add_interface_port TofPet_Conduit EMPTY3 export Input 1
add_interface_port TofPet_Conduit FULL3 export Input 1
add_interface_port TofPet_Conduit DATA_OUT4 export Input 32
add_interface_port TofPet_Conduit EMPTY4 export Input 1
add_interface_port TofPet_Conduit DATA_OUT5 export Input 32
add_interface_port TofPet_Conduit EMPTY5 export Input 1
add_interface_port TofPet_Conduit FULL5 export Input 1
add_interface_port TofPet_Conduit CTRL_FIFO_OUT export Input 32
add_interface_port TofPet_Conduit CTRL_FIFO_OUT_RE export Output 1
add_interface_port TofPet_Conduit CTRL_FIFO_IN export Output 32
add_interface_port TofPet_Conduit CTRL_FIFO_IN_WE export Output 1
add_interface_port TofPet_Conduit NBIT_INOUT export Output 32
add_interface_port TofPet_Conduit COMMAND export Output 32
add_interface_port TofPet_Conduit FULL4 export Input 1
add_interface_port TofPet_Conduit STATUS_WORD export Input 32
add_interface_port TofPet_Conduit READ0 export Output 1
add_interface_port TofPet_Conduit READ1 export Output 1
add_interface_port TofPet_Conduit READ2 export Output 1
add_interface_port TofPet_Conduit READ3 export Output 1
add_interface_port TofPet_Conduit READ4 export Output 1
add_interface_port TofPet_Conduit READ5 export Output 1
add_interface_port TofPet_Conduit USED_WORDS0 export Input 11
add_interface_port TofPet_Conduit USED_WORDS1 export Input 11
add_interface_port TofPet_Conduit USED_WORDS2 export Input 11
add_interface_port TofPet_Conduit USED_WORDS3 export Input 11
add_interface_port TofPet_Conduit USED_WORDS4 export Input 11
add_interface_port TofPet_Conduit USED_WORDS5 export Input 11

